name: Daily Defence News Digest

on:
  schedule:
    # Runs at 06:00 UTC every day (adjust timezone as needed)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  fetch-and-send:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run news aggregator
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
      run: |
        python defence_news_monitor.py
        
    - name: Upload database artifact
      uses: actions/upload-artifact@v3
      with:
        name: defence-news-db
        path: defence_news.db
        retention-days: 30
        
    - name: Commit and push database updates
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add defence_news.db
        git diff --quiet && git diff --staged --quiet || git commit -m "Update seen articles database [automated]"
        git push
      continue-on-error: true
